name: "WizSmith Edge Hub"
version: "1.0.0"
slug: "wizsmith_edge_hub"
description: "Secure HA-to-OpenRemote edge bridge (offline capable)"
arch:
  - aarch64
startup: services
boot: auto
options:
  mqtt_host: "homeassistant.local"
  mqtt_port: 1883
  mqtt_user: "wizha"
  mqtt_pass: "Pa$$w0rd123"
  or_ws_url: "wss://74.208.69.198:8443/ws"
schema:
  mqtt_host: str
  mqtt_port: int
  mqtt_user: str
  mqtt_pass: password
  or_ws_url: str
